from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 717)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-81, -21, 1111, 691))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 170, 0, 255), stop:1 rgba(85, 255, 0, 255));")
        self.widget.setObjectName("widget")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(70, 20, 1061, 101))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(22)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("background-color: rgba(255, 170, 0, 150); color: white;")
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(70, 150, 511, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 200);")
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.widget)
        self.tableWidget_3.setGeometry(QtCore.QRect(115, 241, 581, 241))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setStyleSheet("background-color: white; alternate-background-color: rgba(200, 200, 200, 50);")
        self.tableWidget_3.setColumnCount(3)
        self.tableWidget_3.setRowCount(5)
        self.tableWidget_3.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        # item assignments...
        self.pushButton_Seyahat_Sec_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_Seyahat_Sec_3.setGeometry(QtCore.QRect(120, 560, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.pushButton_Seyahat_Sec_3.setFont(font)
        self.pushButton_Seyahat_Sec_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Seyahat_Sec_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_Seyahat_Sec_3.setStyleSheet("background-color: rgba(255, 170, 0, 150); color: white; border-radius: 10px;")
        self.pushButton_Seyahat_Sec_3.setObjectName("pushButton_Seyahat_Sec_3")
        self.pushButton_Seyahat_Rota = QtWidgets.QPushButton(self.widget)
        self.pushButton_Seyahat_Rota.setGeometry(QtCore.QRect(440, 560, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.pushButton_Seyahat_Rota.setFont(font)
        self.pushButton_Seyahat_Rota.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Seyahat_Rota.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_Seyahat_Rota.setStyleSheet("background-color: rgba(255, 170, 0, 150); color: white; border-radius: 10px;")
        self.pushButton_Seyahat_Rota.setObjectName("pushButton_Seyahat_Rota")
        self.pushButton_Seyahat_Sifirla = QtWidgets.QPushButton(self.widget)
        self.pushButton_Seyahat_Sifirla.setGeometry(QtCore.QRect(750, 560, 251, 81))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(12)
        self.pushButton_Seyahat_Sifirla.setFont(font)
        self.pushButton_Seyahat_Sifirla.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_Seyahat_Sifirla.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pushButton_Seyahat_Sifirla.setStyleSheet("background-color: rgba(255, 170, 0, 150); color: white; border-radius: 10px;")
        self.pushButton_Seyahat_Sifirla.setObjectName("pushButton_Seyahat_Sifirla")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "İKÜ SEYAHAT PLANLAMA UYGULAMASI"))
        self.label_6.setText(_translate("MainWindow", "Kişisel Seyahat Rotası Oluşturma"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Rota Adı"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Konaklama Tesisi"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Konaklama Tesisi Fiyatı"))
        self.pushButton_Seyahat_Sec_3.setText(_translate("MainWindow", "Kaydet"))
        self.pushButton_Seyahat_Rota.setText(_translate("MainWindow", "Kaydedilen Rotaları Göster"))
        self.pushButton_Seyahat_Sifirla.setText(_translate("MainWindow", "Kaydedilen Rotaları Sıfırla"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
