# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1119, 630)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 50, 1021, 531))
        self.label.setStyleSheet("background-color: rgb(125, 62, 0);\n"
"border-radius: 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_ikugames = QtWidgets.QLabel(Form)
        self.label_ikugames.setGeometry(QtCore.QRect(70, 60, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_ikugames.setFont(font)
        self.label_ikugames.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border-radius: 10px;")
        self.label_ikugames.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ikugames.setObjectName("label_ikugames")
        self.pushButton_cikis = QtWidgets.QPushButton(Form)
        self.pushButton_cikis.setGeometry(QtCore.QRect(970, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cikis.setFont(font)
        self.pushButton_cikis.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(168, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(176, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.pushButton_cikis.setObjectName("pushButton_cikis")
        self.pushButton_yemekekle = QtWidgets.QPushButton(Form)
        self.pushButton_yemekekle.setGeometry(QtCore.QRect(840, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_yemekekle.setFont(font)
        self.pushButton_yemekekle.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pushButton_yemekekle.setObjectName("pushButton_yemekekle")
        self.label_menu = QtWidgets.QLabel(Form)
        self.label_menu.setGeometry(QtCore.QRect(80, 120, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_menu.setFont(font)
        self.label_menu.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border-radius: 10px;")
        self.label_menu.setAlignment(QtCore.Qt.AlignCenter)
        self.label_menu.setObjectName("label_menu")
        self.label_siparisler = QtWidgets.QLabel(Form)
        self.label_siparisler.setGeometry(QtCore.QRect(570, 120, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_siparisler.setFont(font)
        self.label_siparisler.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border-radius: 10px;")
        self.label_siparisler.setAlignment(QtCore.Qt.AlignCenter)
        self.label_siparisler.setObjectName("label_siparisler")
        self.label_gecmisim = QtWidgets.QLabel(Form)
        self.label_gecmisim.setGeometry(QtCore.QRect(570, 320, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_gecmisim.setFont(font)
        self.label_gecmisim.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border-radius: 10px;")
        self.label_gecmisim.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gecmisim.setObjectName("label_gecmisim")
        self.tableWidget_menu = QtWidgets.QTableWidget(Form)
        self.tableWidget_menu.setGeometry(QtCore.QRect(80, 160, 471, 361))
        self.tableWidget_menu.setStyleSheet("border-radius: 10px;")
        self.tableWidget_menu.setObjectName("tableWidget_menu")
        self.tableWidget_menu.setColumnCount(3)
        self.tableWidget_menu.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_menu.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_menu.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_menu.setHorizontalHeaderItem(2, item)
        self.tableWidget_siparis = QtWidgets.QTableWidget(Form)
        self.tableWidget_siparis.setGeometry(QtCore.QRect(570, 160, 471, 161))
        self.tableWidget_siparis.setStyleSheet("border-radius: 10px;")
        self.tableWidget_siparis.setObjectName("tableWidget_siparis")
        self.tableWidget_siparis.setColumnCount(4)
        self.tableWidget_siparis.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_siparis.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_siparis.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_siparis.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_siparis.setHorizontalHeaderItem(3, item)
        self.tableWidget_gecmis = QtWidgets.QTableWidget(Form)
        self.tableWidget_gecmis.setGeometry(QtCore.QRect(570, 360, 471, 161))
        self.tableWidget_gecmis.setStyleSheet("border-radius: 10px;")
        self.tableWidget_gecmis.setObjectName("tableWidget_gecmis")
        self.tableWidget_gecmis.setColumnCount(4)
        self.tableWidget_gecmis.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_gecmis.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_gecmis.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_gecmis.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_gecmis.setHorizontalHeaderItem(3, item)
        self.pushButton_guncelle = QtWidgets.QPushButton(Form)
        self.pushButton_guncelle.setGeometry(QtCore.QRect(110, 530, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_guncelle.setFont(font)
        self.pushButton_guncelle.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pushButton_guncelle.setObjectName("pushButton_guncelle")
        self.pushButton_sipariset = QtWidgets.QPushButton(Form)
        self.pushButton_sipariset.setGeometry(QtCore.QRect(370, 530, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_sipariset.setFont(font)
        self.pushButton_sipariset.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pushButton_sipariset.setObjectName("pushButton_sipariset")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_ikugames.setText(_translate("Form", "İKU RESTORAN"))
        self.pushButton_cikis.setText(_translate("Form", "Çıkış Yap"))
        self.pushButton_yemekekle.setText(_translate("Form", "Urun Ekle"))
        self.label_menu.setText(_translate("Form", "Menü"))
        self.label_siparisler.setText(_translate("Form", "Aktif Siparişler"))
        self.label_gecmisim.setText(_translate("Form", "Sipariş Geçmişim"))
        item = self.tableWidget_menu.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Ad"))
        item = self.tableWidget_menu.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Fiyat"))
        item = self.tableWidget_menu.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Stok"))
        item = self.tableWidget_siparis.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Sipariş No"))
        item = self.tableWidget_siparis.horizontalHeaderItem(1)
        item.setText(_translate("Form", "İçerik"))
        item = self.tableWidget_siparis.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Müşteri Adı"))
        item = self.tableWidget_siparis.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Adres"))
        item = self.tableWidget_gecmis.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Sipariş No"))
        item = self.tableWidget_gecmis.horizontalHeaderItem(1)
        item.setText(_translate("Form", "İçerik"))
        item = self.tableWidget_gecmis.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Müşteri Adı"))
        item = self.tableWidget_gecmis.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Adres"))
        self.pushButton_guncelle.setText(_translate("Form", "Stok Güncelle"))
        self.pushButton_sipariset.setText(_translate("Form", "Sipariş Et"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
