# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ekle.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(447, 501)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 50, 351, 401))
        self.label.setStyleSheet("background-color: rgb(125, 62, 0);\n"
"border-radius: 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_ikurestoran = QtWidgets.QLabel(Form)
        self.label_ikurestoran.setGeometry(QtCore.QRect(90, 60, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_ikurestoran.setFont(font)
        self.label_ikurestoran.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border-radius: 10px;")
        self.label_ikurestoran.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ikurestoran.setObjectName("label_ikurestoran")
        self.label_ekle = QtWidgets.QLabel(Form)
        self.label_ekle.setGeometry(QtCore.QRect(80, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_ekle.setFont(font)
        self.label_ekle.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border-radius: 10px;")
        self.label_ekle.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ekle.setObjectName("label_ekle")
        self.lineEdit_ad = QtWidgets.QLineEdit(Form)
        self.lineEdit_ad.setGeometry(QtCore.QRect(90, 140, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_ad.setFont(font)
        self.lineEdit_ad.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_ad.setText("")
        self.lineEdit_ad.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_ad.setObjectName("lineEdit_ad")
        self.lineEdit_fiyat = QtWidgets.QLineEdit(Form)
        self.lineEdit_fiyat.setGeometry(QtCore.QRect(90, 210, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_fiyat.setFont(font)
        self.lineEdit_fiyat.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_fiyat.setText("")
        self.lineEdit_fiyat.setObjectName("lineEdit_fiyat")
        self.lineEdit_stok = QtWidgets.QLineEdit(Form)
        self.lineEdit_stok.setGeometry(QtCore.QRect(90, 280, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_stok.setFont(font)
        self.lineEdit_stok.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color: rgb(255, 255, 255);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_stok.setText("")
        self.lineEdit_stok.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_stok.setObjectName("lineEdit_stok")
        self.pushButton_ekle = QtWidgets.QPushButton(Form)
        self.pushButton_ekle.setGeometry(QtCore.QRect(90, 360, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ekle.setFont(font)
        self.pushButton_ekle.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pushButton_ekle.setObjectName("pushButton_ekle")
        self.pushButton_iptal = QtWidgets.QPushButton(Form)
        self.pushButton_iptal.setGeometry(QtCore.QRect(240, 360, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_iptal.setFont(font)
        self.pushButton_iptal.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(168, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(176, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.pushButton_iptal.setObjectName("pushButton_iptal")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_ikurestoran.setText(_translate("Form", "İKU RESTORAN"))
        self.label_ekle.setText(_translate("Form", "Ürün Ekle"))
        self.lineEdit_ad.setPlaceholderText(_translate("Form", "Ad"))
        self.lineEdit_fiyat.setPlaceholderText(_translate("Form", "Fiyat"))
        self.lineEdit_stok.setPlaceholderText(_translate("Form", "Stok"))
        self.pushButton_ekle.setText(_translate("Form", "Ekle"))
        self.pushButton_iptal.setText(_translate("Form", "İptal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
