# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anasayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1121, 632)
        Form.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 50, 1021, 531))
        self.label.setStyleSheet("background-color: rgb(25, 25, 25);\n"
"border-radius: 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_catflix = QtWidgets.QLabel(Form)
        self.label_catflix.setGeometry(QtCore.QRect(70, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_catflix.setFont(font)
        self.label_catflix.setStyleSheet("color: rgb(170, 0, 0);\n"
"background-color: rgb(25, 25, 25);\n"
"border-radius: 10px;")
        self.label_catflix.setAlignment(QtCore.Qt.AlignCenter)
        self.label_catflix.setObjectName("label_catflix")
        self.lineEdit_arama = QtWidgets.QLineEdit(Form)
        self.lineEdit_arama.setGeometry(QtCore.QRect(210, 60, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_arama.setFont(font)
        self.lineEdit_arama.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 255, 255);")
        self.lineEdit_arama.setText("")
        self.lineEdit_arama.setObjectName("lineEdit_arama")
        self.pushButton_cikis = QtWidgets.QPushButton(Form)
        self.pushButton_cikis.setGeometry(QtCore.QRect(950, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cikis.setFont(font)
        self.pushButton_cikis.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(168, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(176, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.pushButton_cikis.setObjectName("pushButton_cikis")
        self.pushButton_ekle = QtWidgets.QPushButton(Form)
        self.pushButton_ekle.setGeometry(QtCore.QRect(850, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ekle.setFont(font)
        self.pushButton_ekle.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pushButton_ekle.setObjectName("pushButton_ekle")
        self.tableWidget_icerik = QtWidgets.QTableWidget(Form)
        self.tableWidget_icerik.setGeometry(QtCore.QRect(80, 160, 471, 361))
        self.tableWidget_icerik.setStyleSheet("border-radius: 10px;")
        self.tableWidget_icerik.setObjectName("tableWidget_icerik")
        self.tableWidget_icerik.setColumnCount(4)
        self.tableWidget_icerik.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(170, 0, 0))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        self.tableWidget_icerik.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_icerik.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_icerik.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_icerik.setHorizontalHeaderItem(3, item)
        self.tableWidget_izleliste = QtWidgets.QTableWidget(Form)
        self.tableWidget_izleliste.setGeometry(QtCore.QRect(570, 160, 471, 161))
        self.tableWidget_izleliste.setStyleSheet("border-radius: 10px;")
        self.tableWidget_izleliste.setObjectName("tableWidget_izleliste")
        self.tableWidget_izleliste.setColumnCount(4)
        self.tableWidget_izleliste.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_izleliste.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_izleliste.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_izleliste.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_izleliste.setHorizontalHeaderItem(3, item)
        self.label_izlemegecmis = QtWidgets.QLabel(Form)
        self.label_izlemegecmis.setGeometry(QtCore.QRect(570, 320, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_izlemegecmis.setFont(font)
        self.label_izlemegecmis.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border-radius: 10px;")
        self.label_izlemegecmis.setAlignment(QtCore.Qt.AlignCenter)
        self.label_izlemegecmis.setObjectName("label_izlemegecmis")
        self.label_izlemeliste = QtWidgets.QLabel(Form)
        self.label_izlemeliste.setGeometry(QtCore.QRect(570, 120, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_izlemeliste.setFont(font)
        self.label_izlemeliste.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border-radius: 10px;")
        self.label_izlemeliste.setAlignment(QtCore.Qt.AlignCenter)
        self.label_izlemeliste.setObjectName("label_izlemeliste")
        self.label_icerik = QtWidgets.QLabel(Form)
        self.label_icerik.setGeometry(QtCore.QRect(80, 120, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_icerik.setFont(font)
        self.label_icerik.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: transparent;\n"
"border-radius: 10px;")
        self.label_icerik.setAlignment(QtCore.Qt.AlignCenter)
        self.label_icerik.setObjectName("label_icerik")
        self.tableWidget_izlegecmis = QtWidgets.QTableWidget(Form)
        self.tableWidget_izlegecmis.setGeometry(QtCore.QRect(570, 360, 471, 161))
        self.tableWidget_izlegecmis.setStyleSheet("border-radius: 10px;")
        self.tableWidget_izlegecmis.setObjectName("tableWidget_izlegecmis")
        self.tableWidget_izlegecmis.setColumnCount(4)
        self.tableWidget_izlegecmis.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_izlegecmis.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_izlegecmis.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_izlegecmis.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_izlegecmis.setHorizontalHeaderItem(3, item)
        self.pushButton_izle = QtWidgets.QPushButton(Form)
        self.pushButton_izle.setGeometry(QtCore.QRect(80, 530, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_izle.setFont(font)
        self.pushButton_izle.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pushButton_izle.setObjectName("pushButton_izle")
        self.pushButton_izlemelisteekle = QtWidgets.QPushButton(Form)
        self.pushButton_izlemelisteekle.setGeometry(QtCore.QRect(320, 530, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_izlemelisteekle.setFont(font)
        self.pushButton_izlemelisteekle.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pushButton_izlemelisteekle.setObjectName("pushButton_izlemelisteekle")
        self.pushButton_izlemelistesil = QtWidgets.QPushButton(Form)
        self.pushButton_izlemelistesil.setGeometry(QtCore.QRect(560, 530, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_izlemelistesil.setFont(font)
        self.pushButton_izlemelistesil.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(168, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(176, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.pushButton_izlemelistesil.setObjectName("pushButton_izlemelistesil")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_catflix.setText(_translate("Form", "CATFLIX"))
        self.lineEdit_arama.setPlaceholderText(_translate("Form", "Film, Dizi"))
        self.pushButton_cikis.setText(_translate("Form", "Çıkış Yap"))
        self.pushButton_ekle.setText(_translate("Form", "İçerik Ekle"))
        item = self.tableWidget_icerik.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Tür"))
        item = self.tableWidget_icerik.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Ad"))
        item = self.tableWidget_icerik.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Yönetmen"))
        item = self.tableWidget_icerik.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Süre"))
        item = self.tableWidget_izleliste.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Tür"))
        item = self.tableWidget_izleliste.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Ad"))
        item = self.tableWidget_izleliste.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Yönetmen"))
        item = self.tableWidget_izleliste.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Süre"))
        self.label_izlemegecmis.setText(_translate("Form", "İzleme Geçmişim"))
        self.label_izlemeliste.setText(_translate("Form", "İzleme Listem"))
        self.label_icerik.setText(_translate("Form", "İçerikler"))
        item = self.tableWidget_izlegecmis.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Tür"))
        item = self.tableWidget_izlegecmis.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Ad"))
        item = self.tableWidget_izlegecmis.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Yönetmen"))
        item = self.tableWidget_izlegecmis.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Süre"))
        self.pushButton_izle.setText(_translate("Form", "İzle"))
        self.pushButton_izlemelisteekle.setText(_translate("Form", "Daha sonra izle"))
        self.pushButton_izlemelistesil.setText(_translate("Form", "İzleme listesinden sil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
