from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Egzersiz(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-160, -100, 1271, 731))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(230, 100, 781, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(0, 85, 255);\n"
                                   "color: rgb(255, 255, 255);\n"
                                    "border-radius: 20px;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton_egzersizekle = QtWidgets.QPushButton(self.widget)
        self.pushButton_egzersizekle.setGeometry(QtCore.QRect(320, 500, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Light")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_egzersizekle.setFont(font)
        self.pushButton_egzersizekle.setStyleSheet("\n"
                                                     "background-color: rgb(0, 85, 255);\n" 
                                                     "color: rgb(255, 255, 255);\n" # Önceki renk burada
                                                     "border-radius: 30px;")
        self.pushButton_egzersizekle.setObjectName("pushButton_egzersizekle")
        self.pushButton_egzersizekle_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_egzersizekle_2.setGeometry(QtCore.QRect(700, 500, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Light")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_egzersizekle_2.setFont(font)
        self.pushButton_egzersizekle_2.setStyleSheet("\n"
                                                      "background-color: rgb(0, 85, 255);\n"
                                                      "color: rgb(255, 255, 255);\n"  
                                                      "border-radius: 30px;")
        self.pushButton_egzersizekle_2.setObjectName("pushButton_egzersizekle_2")
        self.pushButton_egzersizekle_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_egzersizekle_3.setGeometry(QtCore.QRect(490, 610, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Display Light")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_egzersizekle_3.setFont(font)
        self.pushButton_egzersizekle_3.setStyleSheet("\n"
                                                      "background-color: rgb(0, 85, 255);\n"
                                                      "color: rgb(255, 255, 255);\n"  # Önceki renk burada
                                                      "border-radius: 30px;")
        self.pushButton_egzersizekle_3.setObjectName("pushButton_egzersizekle_3")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(310, 190, 651, 281))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                        "border-radius: 15px;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">i - NABIZ </span></p><p><span style=\" font-size:10pt;\">Kişisel Sağlık Sistemi</span></p></body></html>"))
        self.pushButton_egzersizekle.setText(_translate("MainWindow", "Egzersiz Ekle"))
        self.pushButton_egzersizekle_2.setText(_translate("MainWindow", "Egzersiz Sil"))
        self.pushButton_egzersizekle_3.setText(_translate("MainWindow", "Geri"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Egzersiz Adı"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Egzersiz Süresi"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tekrar Sayısı"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Egzersiz Açıklaması"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Squat"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "N/A (Tekrar sayısıyla yapılır)"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "12"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "Ayaklar omuz genişliğinde açık, sırt dik ve göğüs dışa dönük şekilde durun. Dizlerinizi bükerek kalçanızı geriye doğru itin ve çömelin. Dizleriniz bükülme açınızı aşmadan yavaşça yukarı doğru kalkın."))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Push-up"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "N/A (Tekrar sayısıyla yapılır)"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "Yere yüz üstü uzanın, ellerinizi omuz genişliği kadar açarak yere dayayın. Vücudunuzu kollarınızı kullanarak yukarı doğru kaldırın ve tekrar yavaşça aşağı indirin."))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "Plank"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "30 saniye"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "N/A"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "Dirsekleriniz ve ayak parmaklarınız üzerinde yere yüz üstü uzanın. Vücudunuzu düz bir çizgi olacak şekilde tutun, karın kaslarınızı sıkın ve pozisyonu koruyun."))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Lunges"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "N/A (Tekrar sayısıyla yapılır)"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "10 (Her bacak için)"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "Ayaklarınızı omuz genişliğinde açın, bir adım öne atın ve ön diziniz 90 derece olacak şekilde bükün. Ardından, geriye doğru adım atın ve diğer bacağınızla aynı hareketi yapın."))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Egzersiz()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
