# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Randevu_al.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(988, 715)
        MainWindow.setStyleSheet("#centralwidget{background-color: rgb(0, 0, 0);}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 951, 641))
        self.label.setStyleSheet("border-radius:15;\n"
"background-color: rgb(0, 85, 127);\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 40, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 560, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"QPushButton{background-color: rgb(189, 42, 46);\n"
"color:white;\n"
"border-radius:10;}\n"
"QPushButton::hover{background-color: rgb(47, 179, 0);}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 360, 201, 41))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"border: 2px solid black;\n"
"border-radius:8px;\n"
"padding:5px\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setDragEnabled(False)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 160, 201, 41))
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border: 2px solid black;\n"
"border-radius:8px;\n"
"padding:5px\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setMaxLength(11)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 260, 201, 41))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"border: 2px solid black;\n"
"border-radius:8px;\n"
"padding:5px\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.lineEdit_4.setFrame(True)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setDragEnabled(False)
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_3.setStyleSheet("color:white")
        self.label_3.setIndent(-1)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(230, 500, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"        border: 1px solid gray;\n"
"        border-radius: 4px;\n"
"        padding: 0 8px;\n"
"        selection-background-color: darkgray;\n"
"    }\n"
"\n"
"QDateEdit::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.dateEdit.setWrapping(False)
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setReadOnly(False)
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.dateEdit.setAccelerated(False)
        self.dateEdit.setKeyboardTracking(False)
        self.dateEdit.setProperty("showGroupSeparator", True)
        self.dateEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2024, 5, 12), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2024, 3, 28), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setMaximumDate(QtCore.QDate(2024, 5, 12))
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(QtCore.QDate(2024, 3, 28))
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(450, 500, 181, 41))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.timeEdit.setFont(font)
        self.timeEdit.setAutoFillBackground(False)
        self.timeEdit.setStyleSheet("QTimeEdit {\n"
"\n"
"        border: 1px solid gray;\n"
"        border-radius: 5px;\n"
"        padding: 0 8px;\n"
"        selection-background-color: darkgray;\n"
"\n"
"\n"
"    }\n"
"\n"
"QTimeEdit::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.timeEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2024, 6, 12), QtCore.QTime(15, 30, 0)))
        self.timeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2024, 3, 28), QtCore.QTime(15, 30, 0)))
        self.timeEdit.setMaximumDate(QtCore.QDate(2024, 6, 12))
        self.timeEdit.setMinimumDate(QtCore.QDate(2024, 3, 28))
        self.timeEdit.setMaximumTime(QtCore.QTime(15, 30, 0))
        self.timeEdit.setMinimumTime(QtCore.QTime(15, 30, 0))
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit.setCalendarPopup(True)
        self.timeEdit.setTime(QtCore.QTime(15, 30, 0))
        self.timeEdit.setObjectName("timeEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(510, 100, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_4.setStyleSheet("color:white")
        self.label_4.setIndent(-1)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_4.setObjectName("label_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(410, 150, 431, 331))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 560, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{background-color: rgb(189, 42, 46);\n"
"color:white;\n"
"border-radius:10;}\n"
"QPushButton::hover{background-color: rgb(47, 179, 0);}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 988, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "İKU Halı Saha Randevu Sistemi"))
        self.pushButton.setText(_translate("MainWindow", "Randevu Al"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Soyad"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Üyelik ID"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Ad "))
        self.label_3.setText(_translate("MainWindow", "Kişi Bilgileri"))
        self.label_4.setText(_translate("MainWindow", "Saha Bilgileri"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ad"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Konum"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fiyat"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Durumu"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Şampiyon Halısaha"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Üçyüzlü"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "1400"))
        item = self.tableWidget.item(0, 3)
        item.setText(_translate("MainWindow", "Randevusuz"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "Sarılar Halısaha"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "Bakırköy"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "1300"))
        item = self.tableWidget.item(1, 3)
        item.setText(_translate("MainWindow", "Randevusuz"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "ŞutVakti Futbol Arena\n"
"\n"
""))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "Kadıköy"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "2000"))
        item = self.tableWidget.item(2, 3)
        item.setText(_translate("MainWindow", "Randevusuz"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "Gol Master Arena\n"
"\n"
""))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "Beşiktaş"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "1800"))
        item = self.tableWidget.item(3, 3)
        item.setText(_translate("MainWindow", "Randevusuz"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "Net Gol Spor Merkezi\n"
"\n"
""))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "Şişli"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "1900"))
        item = self.tableWidget.item(4, 3)
        item.setText(_translate("MainWindow", "Randevusuz"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "Süper Lig Futbol Sahası\n"
"\n"
""))
        item = self.tableWidget.item(5, 1)
        item.setText(_translate("MainWindow", "Üsküdar"))
        item = self.tableWidget.item(5, 2)
        item.setText(_translate("MainWindow", "2200"))
        item = self.tableWidget.item(5, 3)
        item.setText(_translate("MainWindow", "Randevusuz"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "Defans Duvarı Futbol Sahası\n"
"\n"
""))
        item = self.tableWidget.item(6, 1)
        item.setText(_translate("MainWindow", "Bakırköy"))
        item = self.tableWidget.item(6, 2)
        item.setText(_translate("MainWindow", "2100"))
        item = self.tableWidget.item(6, 3)
        item.setText(_translate("MainWindow", "Randevusuz"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "Fair Play Futbol Merkezi\n"
"\n"
""))
        item = self.tableWidget.item(7, 1)
        item.setText(_translate("MainWindow", "Beylikdüzü"))
        item = self.tableWidget.item(7, 2)
        item.setText(_translate("MainWindow", "1650"))
        item = self.tableWidget.item(7, 3)
        item.setText(_translate("MainWindow", "Randevusuz"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "Zafer Alanı Spor Kompleksi\n"
"\n"
""))
        item = self.tableWidget.item(8, 1)
        item.setText(_translate("MainWindow", "Avcılar"))
        item = self.tableWidget.item(8, 2)
        item.setText(_translate("MainWindow", "1750"))
        item = self.tableWidget.item(8, 3)
        item.setText(_translate("MainWindow", "Randevusuz"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "Kaleci Kalesi Arena\n"
"\n"
""))
        item = self.tableWidget.item(9, 1)
        item.setText(_translate("MainWindow", "Kartal"))
        item = self.tableWidget.item(9, 2)
        item.setText(_translate("MainWindow", "1600"))
        item = self.tableWidget.item(9, 3)
        item.setText(_translate("MainWindow", "Randevusuz"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("MainWindow", "Geri"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
