# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tarih.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tarih(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(966, 779)
        MainWindow.setStyleSheet(".QWidget {\n"
"   background-color: beige;\n"
"}\n"
"\n"
"/* Nice Windows-XP-style password character. */\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    lineedit-password-character: 9679;\n"
"}\n"
"\n"
"/* We provide a min-width and min-height for push buttons\n"
"   so that they look elegant regardless of the width of the text. */\n"
"QPushButton {\n"
"    background-color: palegoldenrod;\n"
"    border-width: 2px;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-radius: 5;\n"
"    padding: 3px;\n"
"    min-width: 9ex;\n"
"    min-height: 2.5ex;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"   background-color: khaki;\n"
"}\n"
"\n"
"/* Increase the padding, so the text is shifted when the button is\n"
"   pressed. */\n"
"QPushButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: #d0d67c;\n"
"}\n"
"\n"
"QLabel, QAbstractButton {\n"
"    font: bold;\n"
"}\n"
"\n"
"/* Mark mandatory fields with a brownish color. */\n"
".mandatory {\n"
"    color: brown;\n"
"}\n"
"\n"
"/* Bold text on status bar looks awful. */\n"
"QStatusBar QLabel {\n"
"   font: normal;\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"    border-width: 1;\n"
"    border-color: darkkhaki;\n"
"    border-style: solid;\n"
"    border-radius: 2;\n"
"}\n"
"\n"
"QComboBox, QLineEdit, QSpinBox, QTextEdit, QListView {\n"
"    background-color: cornsilk;\n"
"    selection-color: #0a214c; \n"
"    selection-background-color: #C19A6B;\n"
"}\n"
"\n"
"QListView {\n"
"    show-decoration-selected: 1;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background-color: wheat;\n"
"}\n"
"\n"
"/* We reserve 1 pixel space in padding. When we get the focus,\n"
"   we kill the padding and enlarge the border. This makes the items\n"
"   glow. */\n"
"QLineEdit, QFrame {\n"
"    border-width: 2px;\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border-color: darkkhaki;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/* As mentioned above, eliminate the padding and increase the border. */\n"
"QLineEdit:focus, QFrame:focus {\n"
"    border-width: 3px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* A QLabel is a QFrame ... */\n"
"QLabel {\n"
"    border: none;\n"
"    padding: 0;\n"
"    background: none;\n"
"}\n"
"\n"
"/* A QToolTip is a QLabel ... */\n"
"QToolTip {\n"
"    border: 2px solid darkkhaki;\n"
"    padding: 5px;\n"
"    border-radius: 3px;\n"
"    opacity: 200;\n"
"}\n"
"\n"
"/* Nice to have the background color change when hovered. */\n"
"QRadioButton:hover, QCheckBox:hover {\n"
"    background-color: wheat;\n"
"}\n"
"\n"
"/* Force the dialog\'s buttons to follow the Windows guidelines. */\n"
"QDialogButtonBox {\n"
"    button-layout: 0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(310, 0, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.table_liste = QtWidgets.QTableWidget(self.centralwidget)
        self.table_liste.setGeometry(QtCore.QRect(10, 380, 941, 291))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.table_liste.setFont(font)
        for row_number in range(1, 51):
            for column_number in range(self.table_liste.columnCount()):
                item = QtWidgets.QTableWidgetItem()
                item.setTextAlignment(QtCore.Qt.AlignCenter)
                self.table_liste.setItem(row_number - 1, column_number, item)
        self.table_liste.setRowCount(100)
        self.table_liste.setColumnCount(8)
        self.table_liste.setObjectName("table_liste")
        self.table_liste.setHorizontalHeaderLabels(["Olay No", "Şahsiyet", "Yaşadığı Dönem", "Olay Adı", "Tarih", "Dönem Adı", "Başlangıç Tarihi", "Bitiş Tarihi"])
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 3, 271, 301))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.line_olayno = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.line_olayno.setFont(font)
        self.line_olayno.setStyleSheet("background-color: rgb(188, 255, 188);")
        self.line_olayno.setObjectName("line_olayno")
        self.horizontalLayout.addWidget(self.line_olayno)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.line_sahsiyet = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.line_sahsiyet.setFont(font)
        self.line_sahsiyet.setStyleSheet("background-color: rgb(188, 255, 188);")
        self.line_sahsiyet.setObjectName("line_sahsiyet")
        self.horizontalLayout_2.addWidget(self.line_sahsiyet)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.line_yasadigidonem = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.line_yasadigidonem.setFont(font)
        self.line_yasadigidonem.setStyleSheet("background-color: rgb(188, 255, 188);")
        self.line_yasadigidonem.setObjectName("line_yasadigidonem")
        self.horizontalLayout_3.addWidget(self.line_yasadigidonem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.line_olayadi = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.line_olayadi.setFont(font)
        self.line_olayadi.setStyleSheet("background-color: rgb(188, 255, 188);")
        self.line_olayadi.setObjectName("line_olayadi")
        self.horizontalLayout_4.addWidget(self.line_olayadi)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.line_tarih = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.line_tarih.setFont(font)
        self.line_tarih.setStyleSheet("background-color: rgb(188, 255, 188);")
        self.line_tarih.setObjectName("line_tarih")
        self.horizontalLayout_5.addWidget(self.line_tarih)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.btn_cikis = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cikis.setGeometry(QtCore.QRect(857, 680, 91, 34))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_cikis.setFont(font)
        self.btn_cikis.setObjectName("btn_cikis")
        self.line_olay = QtWidgets.QTextEdit(self.centralwidget)
        self.line_olay.setGeometry(QtCore.QRect(310, 30, 631, 131))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.line_olay.setFont(font)
        self.line_olay.setStyleSheet("background-color: rgb(188, 255, 188);")
        self.line_olay.setObjectName("line_olay")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(310, 170, 291, 164))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.line_donemadi = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.line_donemadi.setFont(font)
        self.line_donemadi.setStyleSheet("background-color: rgb(188, 255, 188);")
        self.line_donemadi.setObjectName("line_donemadi")
        self.verticalLayout_3.addWidget(self.line_donemadi)
        self.line_baslangictarihi = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.line_baslangictarihi.setFont(font)
        self.line_baslangictarihi.setStyleSheet("background-color: rgb(188, 255, 188);")
        self.line_baslangictarihi.setObjectName("line_baslangictarihi")
        self.verticalLayout_3.addWidget(self.line_baslangictarihi)
        self.line_bitistarihi = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.line_bitistarihi.setFont(font)
        self.line_bitistarihi.setStyleSheet("background-color: rgb(188, 255, 188);")
        self.line_bitistarihi.setObjectName("line_bitistarihi")
        self.verticalLayout_3.addWidget(self.line_bitistarihi)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 340, 931, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.lneAra = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.lneAra.setFont(font)
        self.lneAra.setStyleSheet("background-color: rgb(188, 255, 188);")
        self.lneAra.setObjectName("lneAra")
        self.horizontalLayout_8.addWidget(self.lneAra)
        self.btn_sahsiyet = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_sahsiyet.setFont(font)
        self.btn_sahsiyet.setStyleSheet("background-color: rgb(219, 235, 255);")
        self.btn_sahsiyet.setObjectName("btn_sahsiyet")
        self.horizontalLayout_8.addWidget(self.btn_sahsiyet)
        self.btn_yasadigidonem = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_yasadigidonem.setFont(font)
        self.btn_yasadigidonem.setStyleSheet("background-color: rgb(219, 235, 255);")
        self.btn_yasadigidonem.setObjectName("btn_yasadigidonem")
        self.horizontalLayout_8.addWidget(self.btn_yasadigidonem)
        self.btn_olayadi = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_olayadi.setFont(font)
        self.btn_olayadi.setStyleSheet("background-color: rgb(219, 235, 255);")
        self.btn_olayadi.setObjectName("btn_olayadi")
        self.horizontalLayout_8.addWidget(self.btn_olayadi)
        self.btn_tarihi = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_tarihi.setFont(font)
        self.btn_tarihi.setStyleSheet("background-color: rgb(219, 235, 255);")
        self.btn_tarihi.setObjectName("btn_tarihi")
        self.horizontalLayout_8.addWidget(self.btn_tarihi)
        self.btn_donemadi = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_donemadi.setFont(font)
        self.btn_donemadi.setStyleSheet("background-color: rgb(219, 235, 255);")
        self.btn_donemadi.setObjectName("btn_donemadi")
        self.horizontalLayout_8.addWidget(self.btn_donemadi)
        self.btn_listele = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_listele.setFont(font)
        self.btn_listele.setStyleSheet("background-color: rgb(219, 235, 255);")
        self.btn_listele.setObjectName("btn_listele")
        self.horizontalLayout_8.addWidget(self.btn_listele)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(620, 170, 321, 141))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnSil = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnSil.setFont(font)
        self.btnSil.setStyleSheet("background-color: rgb(219, 235, 255);")
        self.btnSil.setObjectName("btnSil")
        self.verticalLayout_4.addWidget(self.btnSil)
        self.btnEkle = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnEkle.setFont(font)
        self.btnEkle.setStyleSheet("background-color: rgb(219, 235, 255);")
        self.btnEkle.setObjectName("btnEkle")
        self.verticalLayout_4.addWidget(self.btnEkle)
        self.btnGuncelle = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnGuncelle.setFont(font)
        self.btnGuncelle.setStyleSheet("background-color: rgb(219, 235, 255);")
        self.btnGuncelle.setObjectName("btnGuncelle")
        self.verticalLayout_4.addWidget(self.btnGuncelle)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 966, 26))
        self.menubar.setObjectName("menubar")
        self.menuYARIDM = QtWidgets.QMenu(self.menubar)
        self.menuYARIDM.setObjectName("menuYARIDM")
        MainWindow.setMenuBar(self.menubar)
        self.actionHAKKINDA = QtWidgets.QAction(MainWindow)
        self.actionHAKKINDA.setObjectName("actionHAKKINDA")
        self.menuHakkinda = QtWidgets.QAction(MainWindow)
        self.menuHakkinda.setObjectName("menuHakkinda")
        self.menuYARIDM.addAction(self.menuHakkinda)
        self.menubar.addAction(self.menuYARIDM.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tarihi Olaylar"))
        self.label_7.setText(_translate("MainWindow", "Olay:"))
        self.label_6.setText(_translate("MainWindow", "Olay No:"))
        self.label.setText(_translate("MainWindow", "Şahsiyet:"))
        self.label_2.setText(_translate("MainWindow", "Yaşadığı Dönem:"))
        self.label_3.setText(_translate("MainWindow", "Olay Adı:"))
        self.label_4.setText(_translate("MainWindow", "Tarihi:"))
        self.btn_cikis.setText(_translate("MainWindow", "Çıkış"))
        self.label_5.setText(_translate("MainWindow", "Dönem Adı:"))
        self.label_8.setText(_translate("MainWindow", "Başlangıç Tarihi"))
        self.label_9.setText(_translate("MainWindow", "Bitiş Tarihi"))
        self.label_15.setText(_translate("MainWindow", "Aranacak Kelime:"))
        self.btn_sahsiyet.setText(_translate("MainWindow", "Şahsiyet"))
        self.btn_yasadigidonem.setText(_translate("MainWindow", "Yaşadığı Dönem"))
        self.btn_olayadi.setText(_translate("MainWindow", "Olay Adı"))
        self.btn_tarihi.setText(_translate("MainWindow", "Tarihi"))
        self.btn_donemadi.setText(_translate("MainWindow", "Dönem Adı"))
        self.btn_listele.setText(_translate("MainWindow", "Tüm Kaydı Listele"))
        self.btnSil.setText(_translate("MainWindow", "Kaydı Sil"))
        self.btnEkle.setText(_translate("MainWindow", "Kayıt Ekle"))
        self.btnGuncelle.setText(_translate("MainWindow", "Kayıt Güncelle"))
        self.menuYARIDM.setTitle(_translate("MainWindow", "Diğer"))
        self.actionHAKKINDA.setText(_translate("MainWindow", "HAKKINDA"))
        self.menuHakkinda.setText(_translate("MainWindow", "Hakkında"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Tarih()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
