# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yönetim.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(981, 572)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 50, 861, 471))
        self.label.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"border-radius:20;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tableWidget_Urun = QtWidgets.QTableWidget(Form)
        self.tableWidget_Urun.setGeometry(QtCore.QRect(100, 120, 351, 331))
        self.tableWidget_Urun.setStyleSheet("")
        self.tableWidget_Urun.setObjectName("tableWidget_Urun")
        self.tableWidget_Urun.setColumnCount(3)
        self.tableWidget_Urun.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Urun.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Urun.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Urun.setHorizontalHeaderItem(2, item)
        self.tableWidget_Siparis = QtWidgets.QTableWidget(Form)
        self.tableWidget_Siparis.setGeometry(QtCore.QRect(510, 120, 351, 331))
        self.tableWidget_Siparis.setStyleSheet("")
        self.tableWidget_Siparis.setObjectName("tableWidget_Siparis")
        self.tableWidget_Siparis.setColumnCount(4)
        self.tableWidget_Siparis.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Siparis.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Siparis.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Siparis.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Siparis.setHorizontalHeaderItem(3, item)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 50, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(510, 50, 351, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.pushButton_Ekle = QtWidgets.QPushButton(Form)
        self.pushButton_Ekle.setGeometry(QtCore.QRect(100, 460, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Ekle.setFont(font)
        self.pushButton_Ekle.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pushButton_Ekle.setObjectName("pushButton_Ekle")
        self.pushButton_Guncelle = QtWidgets.QPushButton(Form)
        self.pushButton_Guncelle.setGeometry(QtCore.QRect(220, 460, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Guncelle.setFont(font)
        self.pushButton_Guncelle.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pushButton_Guncelle.setObjectName("pushButton_Guncelle")
        self.pushButton_Iptal = QtWidgets.QPushButton(Form)
        self.pushButton_Iptal.setGeometry(QtCore.QRect(510, 460, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Iptal.setFont(font)
        self.pushButton_Iptal.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(168, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.pushButton_Iptal.setObjectName("pushButton_Iptal")
        self.pushButton_Sil = QtWidgets.QPushButton(Form)
        self.pushButton_Sil.setGeometry(QtCore.QRect(340, 460, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Sil.setFont(font)
        self.pushButton_Sil.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(168, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(200, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.pushButton_Sil.setObjectName("pushButton_Sil")
        self.pushButton_Geri = QtWidgets.QPushButton(Form)
        self.pushButton_Geri.setGeometry(QtCore.QRect(750, 460, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Geri.setFont(font)
        self.pushButton_Geri.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pushButton_Geri.setObjectName("pushButton_Geri")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.tableWidget_Urun.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Ürün No"))
        item = self.tableWidget_Urun.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Ürün Adı"))
        item = self.tableWidget_Urun.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Stok Miktarı"))
        item = self.tableWidget_Siparis.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Sipariş No"))
        item = self.tableWidget_Siparis.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Ürün"))
        item = self.tableWidget_Siparis.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Miktar"))
        item = self.tableWidget_Siparis.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Detay"))
        self.label_2.setText(_translate("Form", "Ürünler  Tablosu"))
        self.label_3.setText(_translate("Form", "Sipariş Tablosu"))
        self.pushButton_Ekle.setText(_translate("Form", "Ürün Ekle"))
        self.pushButton_Guncelle.setText(_translate("Form", "Stok Güncelle"))
        self.pushButton_Iptal.setText(_translate("Form", "Siparişi İptal Et"))
        self.pushButton_Sil.setText(_translate("Form", "Ürünü Sil"))
        self.pushButton_Geri.setText(_translate("Form", "Geri"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
