# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'egzersizler.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1163, 526)
        MainWindow.setStyleSheet("#centralwidget{\n"
"background-color: rgb(102, 36, 0);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 1121, 451))
        self.label.setStyleSheet("border-radius:15;\n"
"background-color: rgb(255, 107, 26);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 40, 1101, 411))
        self.listWidget.setStyleSheet("QListWidget {\n"
"    background-color: #f0f0f0; /* Arkaplan rengi */\n"
"    color: #333;              /* Yazı rengi */\n"
"    border: 2px solid #ccc;   /* Kenarlık */\n"
"    border-radius:10px\n"
"\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #5682a3; /* Seçili öğenin arkaplan rengi */\n"
"    color: white;              /* Seçili öğenin yazı rengi */\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #dde;   /* Hover arkaplan rengi */\n"
"    color: black;             /* Hover yazı rengi */\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1163, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Adım Egzersizi -> Adım egzersizi, belli bir hızda ve süre boyunca yürüme eylemidir ve genellikle sağlık ve fitness amacıyla yapılır. "))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Bacak Egzersizi -> Bacak  egzersizi, bacakların ön, arka ve yan bölgelerindeki kas gruplarını hedefleyen ve güçlendirilmesini sağlayan fiziksel aktiviteler bütünüdür."))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "Ayakta Şınav Egzersizi -> Ayakta şınav egzersizi, duvara yaslanarak yapılan ve özellikle üst vücut kaslarını çalıştıran bir güçlendirme hareketidir."))
        item = self.listWidget.item(6)
        item.setText(_translate("MainWindow", "Plank Egzersizi ->Plank egzersizi, vücudu düz bir çizgide tutarak dirsekler ve ayak uçları üzerinde sabit bir pozisyonu koruyarak çekirdek kasları güçlendirmeye yönelik bir dayanıklılık egzersizidir."))
        item = self.listWidget.item(8)
        item.setText(_translate("MainWindow", "Burpee Egzersizi -> Burpee egzersizi, zıplama, şınav ve squat hareketlerini birleştirerek tüm vücudu çalıştıran, yüksek yoğunluklu bir kardiyo ve güç antrenmanıdır."))
        item = self.listWidget.item(10)
        item.setText(_translate("MainWindow", "Mekik Egzersizi -> Mekik egzersizi, sırt üstü yatarak bacaklar kıvrılmış haldeyken üst vücudun yerden kaldırılması ve tekrar yere yavaşça indirilmesi işlemiyle karın kaslarını çalıştıran bir güçlendirme hareketidir."))
        item = self.listWidget.item(12)
        item.setText(_translate("MainWindow", "Bisikler Egzersizi ->Bisiklet egzersizi, sırt üstü yatarak pedal çevirme hareketiyle karın kaslarını çalıştırır."))
        item = self.listWidget.item(14)
        item.setText(_translate("MainWindow", "Köprü Egzersizi ->Köprü egzersizi, sırt üstü yatarak ayaklar yere basılıyken kalçaları kaldırıp indirme hareketiyle glute ve alt sırt kaslarını güçlendirir."))
        item = self.listWidget.item(16)
        item.setText(_translate("MainWindow", "Kick Back Egzersizi -> Kick back egzersizi, dört ayak üzerinde dururken bir bacağı geriye doğru düz bir şekilde kaldırıp indirme hareketiyle glute kaslarını çalıştıran bir egzersizdir."))
        item = self.listWidget.item(18)
        item.setText(_translate("MainWindow", "Ters Lunge Egzersizi ->Ters lunge egzersizi, bir bacağın geriye doğru adım atılması ve ardından çömelme hareketi yapılmasıyla bacak ve kalça kaslarını çalıştıran bir egzersizdir."))
        item = self.listWidget.item(20)
        item.setText(_translate("MainWindow", "Squat Egzersizi -> Squat egzersizi, ayaklar omuz genişliğinde açıkken kalçaları geriye doğru iterek çömelme ve ardından tekrar ayağa kalkma hareketiyle bacak ve kalça kaslarını güçlendiren bir egzersizdir."))
        item = self.listWidget.item(22)
        item.setText(_translate("MainWindow", "Diz Üstünde Şınav Egzersizi -> Diz üstünde şınav egzersizi, dizlerin yerde olduğu pozisyonda göğüs ve kol kaslarını çalıştıran bir güçlendirme hareketidir."))
        self.listWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
