# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spor_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 600)
        MainWindow.setStyleSheet("#centralwidget{\n"
"background-color: rgb(102, 36, 0);\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 781, 521))
        self.label.setStyleSheet("border-radius:15;\n"
"background-color: rgb(255, 107, 26);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 120, 201, 41))
        self.lineEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border: 2px solid black;\n"
"border-radius:8px;\n"
"padding:5px\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.lineEdit_2.setMaxLength(25)
        self.lineEdit_2.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 70, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_3.setStyleSheet("color:white")
        self.label_3.setIndent(-1)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 190, 201, 41))
        self.lineEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"border: 2px solid black;\n"
"border-radius:8px;\n"
"padding:5px\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setMaxLength(25)
        self.lineEdit_3.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(60, 260, 201, 41))
        self.lineEdit_4.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"border: 2px solid black;\n"
"border-radius:8px;\n"
"padding:5px\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setMaxLength(3)
        self.lineEdit_4.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(60, 330, 201, 41))
        self.lineEdit_5.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_5.setStyleSheet("QLineEdit{\n"
"border: 2px solid black;\n"
"border-radius:8px;\n"
"padding:5px\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setMaxLength(3)
        self.lineEdit_5.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_5.setClearButtonEnabled(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(60, 400, 201, 41))
        self.lineEdit_6.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_6.setStyleSheet("QLineEdit{\n"
"border: 2px solid black;\n"
"border-radius:8px;\n"
"padding:5px\n"
"}\n"
"\n"
"QLineEdit::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setMaxLength(2)
        self.lineEdit_6.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_6.setClearButtonEnabled(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(460, 70, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_4.setStyleSheet("color:white")
        self.label_4.setIndent(-1)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 470, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("\n"
"QPushButton{\n"
"color:white;\n"
"    background-color: rgb(125, 117, 116);\n"
"border-radius:10;}\n"
"QPushButton::hover{background-color: rgb(0, 34, 53);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(660, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"background-color: rgb(8, 196, 255);\n"
"color:white;\n"
"border-radius:10;}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 34, 53);}\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(460, 120, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"        border: 1px solid gray;\n"
"        border-radius: 4px;\n"
"        padding: 0 8px;\n"
"        selection-background-color: darkgray;\n"
"    }\n"
"\n"
"QComboBox::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(460, 190, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"        border: 1px solid gray;\n"
"        border-radius: 4px;\n"
"        padding: 0 8px;\n"
"        selection-background-color: darkgray;\n"
"    }\n"
"\n"
"QComboBox::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(460, 260, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"        border: 1px solid gray;\n"
"        border-radius: 4px;\n"
"        padding: 0 8px;\n"
"        selection-background-color: darkgray;\n"
"    }\n"
"\n"
"QComboBox::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(460, 330, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("QComboBox {\n"
"        border: 1px solid gray;\n"
"        border-radius: 4px;\n"
"        padding: 0 8px;\n"
"        selection-background-color: darkgray;\n"
"    }\n"
"\n"
"QComboBox::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(460, 400, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("QComboBox {\n"
"        border: 1px solid gray;\n"
"        border-radius: 4px;\n"
"        padding: 0 8px;\n"
"        selection-background-color: darkgray;\n"
"    }\n"
"\n"
"QComboBox::focus{\n"
"border : 2px solid blue;\n"
"border-color: rgb(85, 0, 127)\n"
"\n"
"}")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"background-color: rgb(8, 196, 255);\n"
"color:white;\n"
"border-radius:10;}\n"
"QPushButton::hover{\n"
"background-color: rgb(0, 34, 53);}\n"
"\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Ad Soyad"))
        self.label_3.setText(_translate("MainWindow", "Sporcu Bilgileri"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Spor Dalı"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Boy"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Kilo"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "Yaş"))
        self.label_4.setText(_translate("MainWindow", "Antreman Hareketleri"))
        self.pushButton_4.setText(_translate("MainWindow", "Program Oluştur"))
        self.pushButton.setText(_translate("MainWindow", "Programlarım"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1.Egzersiz"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Adım Egzersizi"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Bacak Kası Egzersizi"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Ayakta Şınav Egzersizi"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Plank Egzersizi"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Burpee Egzersizi"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Mekik Egzersizi"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Bisiklet Egzersizi"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Köprü Egzersizi"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Kick Back Egzersizi"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Ters Lunge"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Squat"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Diz Üstünde Şınav"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "2.Egzersiz"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "2.Egzersiz"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Adım Egzersizi"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Bacak Kası Egzersizi"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Ayakta Şınav Egzersizi"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Plank Egzersizi"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Burpee Egzersizi"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "Mekik Egzersizi"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "Bisiklet Egzersizi"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "Köprü Egzersizi"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "Kick Back Egzersizi"))
        self.comboBox_2.setItemText(10, _translate("MainWindow", "Ters Lunge"))
        self.comboBox_2.setItemText(11, _translate("MainWindow", "Squat"))
        self.comboBox_2.setItemText(12, _translate("MainWindow", "Diz Üstünde Şınav"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "3.Egzersiz"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Adım Egzersizi"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Bacak Kası Egzersizi"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Ayakta Şınav Egzersizi"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Plank Egzersizi"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Burpee Egzersizi"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Mekik Egzersizi"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "Bisiklet Egzersizi"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "Köprü Egzersizi"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "Kick Back Egzersizi"))
        self.comboBox_3.setItemText(10, _translate("MainWindow", "Ters Lunge"))
        self.comboBox_3.setItemText(11, _translate("MainWindow", "Squat"))
        self.comboBox_3.setItemText(12, _translate("MainWindow", "Diz Üstünde Şınav"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "4.Egzersiz"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Adım Egzersizi"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Bacak Kası Egzersizi"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Ayakta Şınav Egzersizi"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Plank Egzersizi"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "Burpee Egzersizi"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "Mekik Egzersizi"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "Bisiklet Egzersizi"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "Köprü Egzersizi"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "Kick Back Egzersizi"))
        self.comboBox_4.setItemText(10, _translate("MainWindow", "Ters Lunge"))
        self.comboBox_4.setItemText(11, _translate("MainWindow", "Squat"))
        self.comboBox_4.setItemText(12, _translate("MainWindow", "Diz Üstünde Şınav"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "5.Egzersiz"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Adım Egzersizi"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Bacak Kası Egzersizi"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "Ayakta Şınav Egzersizi"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "Plank Egzersizi"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "Burpee Egzersizi"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "Mekik Egzersizi"))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "Bisiklet Egzersizi"))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "Köprü Egzersizi"))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "Kick Back Egzersizi"))
        self.comboBox_5.setItemText(10, _translate("MainWindow", "Ters Lunge"))
        self.comboBox_5.setItemText(11, _translate("MainWindow", "Squat"))
        self.comboBox_5.setItemText(12, _translate("MainWindow", "Diz Üstünde Şınav"))
        self.pushButton_2.setText(_translate("MainWindow", "Hareketler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
