# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tarif.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(391, 502)
        Form.setStyleSheet("background-color: rgb(52, 52, 52);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 351, 461))
        self.label.setStyleSheet("background-color: rgb(255, 170, 0);\n"
"border-radius: 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_Kayit = QtWidgets.QLabel(Form)
        self.label_Kayit.setGeometry(QtCore.QRect(80, 40, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_Kayit.setFont(font)
        self.label_Kayit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 170, 0);")
        self.label_Kayit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Kayit.setObjectName("label_Kayit")
        self.lineEdit_yemekadi = QtWidgets.QLineEdit(Form)
        self.lineEdit_yemekadi.setGeometry(QtCore.QRect(55, 100, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_yemekadi.setFont(font)
        self.lineEdit_yemekadi.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:rgba(0,0,0,230);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_yemekadi.setText("")
        self.lineEdit_yemekadi.setObjectName("lineEdit_yemekadi")
        self.lineEdit_malzemeler = QtWidgets.QLineEdit(Form)
        self.lineEdit_malzemeler.setGeometry(QtCore.QRect(55, 180, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_malzemeler.setFont(font)
        self.lineEdit_malzemeler.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:rgba(0,0,0,230);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_malzemeler.setText("")
        self.lineEdit_malzemeler.setObjectName("lineEdit_malzemeler")
        self.lineEdit_tarif = QtWidgets.QLineEdit(Form)
        self.lineEdit_tarif.setGeometry(QtCore.QRect(55, 260, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_tarif.setFont(font)
        self.lineEdit_tarif.setStyleSheet("background-color: rgba(0, 0, 0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(105,118,132,255);\n"
"color:rgba(0,0,0,230);\n"
"padding-bottom:7px;\n"
"")
        self.lineEdit_tarif.setText("")
        self.lineEdit_tarif.setObjectName("lineEdit_tarif")
        self.pushButton_ekle = QtWidgets.QPushButton(Form)
        self.pushButton_ekle.setGeometry(QtCore.QRect(80, 350, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ekle.setFont(font)
        self.pushButton_ekle.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 216, 216);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(163, 163, 163);\n"
"}")
        self.pushButton_ekle.setObjectName("pushButton_ekle")
        self.pushButton_iptal = QtWidgets.QPushButton(Form)
        self.pushButton_iptal.setGeometry(QtCore.QRect(120, 400, 151, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_iptal.setFont(font)
        self.pushButton_iptal.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(168, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(176, 0, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 0, 0);\n"
"}")
        self.pushButton_iptal.setObjectName("pushButton_iptal")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_Kayit.setText(_translate("Form", "Tarif Ekleme"))
        self.lineEdit_yemekadi.setPlaceholderText(_translate("Form", "Yemeğin Adı"))
        self.lineEdit_malzemeler.setPlaceholderText(_translate("Form", "Malzemeler"))
        self.lineEdit_tarif.setPlaceholderText(_translate("Form", "Tarifi"))
        self.pushButton_ekle.setText(_translate("Form", "Tarifi Ekle"))
        self.pushButton_iptal.setText(_translate("Form", "İptal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
